let adminPassword = sessionStorage.getItem('ADMIN_PASSWORD') || '';
let products = [], editingId = null, currentSection = 'catalog';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = value => `${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(value||0))} ₽`;
const title = p => p?.name?.ru || p?.name?.en || `Товар #${p.id}`;
const category = p => p?.cat?.ru || p?.cat?.en || 'Без категории';

function setStatus(text='', ok=true){const el=$('#status');el.textContent=text;el.style.color=ok?'#50c9ff':'#ff7187';el.classList.toggle('visible',Boolean(text));clearTimeout(setStatus.timer);if(text)setStatus.timer=setTimeout(()=>el.classList.remove('visible'),3500)}
async function api(path,options={}){const headers={'X-Admin-Password':adminPassword,...(options.headers||{})};if(!(options.body instanceof FormData))headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false)throw new Error(data.error||data.message||'Не удалось выполнить запрос');return data}

function showDashboard(){$('#loginView').classList.add('hidden');$('#panel').classList.remove('hidden');$('#reloadBtn').classList.remove('hidden');$('#openCreateBtn').classList.remove('hidden');$('#importPriceBtn').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden')}
function updateStats(){const prices=products.map(p=>Number(p.pricePerKg||0)).filter(Boolean),cats=new Set(products.map(category).filter(c=>c!=='Без категории')),complete=products.filter(p=>title(p)&&Number(p.pricePerKg)>0&&p.img).length;$('#totalProducts').textContent=products.length;$('#averagePrice').textContent=money(prices.reduce((a,b)=>a+b,0)/(prices.length||1));$('#totalCategories').textContent=cats.size;$('#catalogHealth').textContent=`${Math.round(complete/(products.length||1)*100)}%`;$('#catalogCaption').textContent=`${products.length} позиций · ${products.filter(p=>p.visible!==false).length} опубликовано`}
async function loadProducts(){setStatus('Обновляем каталог…');const data=await api('/api/admin/products');products=(data.products||[]).sort((a,b)=>(a.sortOrder??9999)-(b.sortOrder??9999));renderProducts();renderCategories();updateStats();showDashboard();setStatus('Каталог обновлён')}

function renderProducts(){const q=($('#search').value||'').trim().toLowerCase(),list=products.filter(p=>JSON.stringify(p).toLowerCase().includes(q));$('#products').innerHTML=list.map(p=>`<article class="product ${p.visible===false?'is-hidden':''}" data-id="${Number(p.id)}"><div class="product-info">${p.img?`<img src="/${esc(p.img)}" alt="">`:'<div class="no-img">◇</div>'}<div><h3>${esc(title(p))}${p.visible===false?'<em>Скрыт</em>':''}</h3><p>${esc(category(p))}</p></div></div><label class="field-suffix"><input class="price" type="number" min="0" step="0.01" value="${Number(p.pricePerKg||0)}"><span>₽/${esc(p.priceUnit||'кг')}</span></label><label class="field-suffix"><input class="pack" type="number" min="0" step="${p.priceUnit==='кг'?'0.1':'1'}" value="${Number(p.packKg||10)}"><span>${esc(p.priceUnit||'кг')}</span></label><div class="actions"><button class="save" data-save type="button">Сохранить</button><button data-toggle title="${p.visible===false?'Опубликовать':'Скрыть'}">${p.visible===false?'◉':'⊘'}</button><button data-edit title="Редактировать">✎</button><button class="danger" data-delete title="Удалить">×</button></div></article>`).join('')||'<div class="empty">Ничего не найдено.</div>'}

async function saveQuick(card){const id=Number(card.dataset.id),p=products.find(x=>Number(x.id)===id),payload={pricePerKg:Number(card.querySelector('.price').value),packKg:Number(card.querySelector('.pack').value)};const data=await api(`/api/admin/products/${id}`,{method:'POST',body:JSON.stringify(payload)});Object.assign(p,data.product);updateStats();setStatus(`Сохранено: ${title(p)}`)}
async function toggleVisible(card){const p=products.find(x=>Number(x.id)===Number(card.dataset.id)),data=await api(`/api/admin/products/${p.id}`,{method:'POST',body:JSON.stringify({visible:p.visible===false})});Object.assign(p,data.product);renderProducts();updateStats();setStatus(p.visible===false?'Товар скрыт':'Товар опубликован')}

function resetForm(){editingId=null;['#newNameRu','#newNameEn','#newCatRu','#newPrice','#newPack','#newImg','#newDescRu'].forEach(id=>$(id).value='');$('#newPriceUnit').value='кг';$('#newVisible').checked=true;$('#uploadStatus').textContent='JPG, PNG или WEBP · до 10 МБ';$('#modalEyebrow').textContent='Новая позиция';$('#createTitle').textContent='Добавить товар';$('#createBtn').textContent='Добавить товар'}
function openCreate(){resetForm();openModal()}
function openEdit(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;editingId=p.id;$('#newNameRu').value=p.name?.ru||'';$('#newNameEn').value=p.name?.en||'';$('#newCatRu').value=p.cat?.ru||'';$('#newPrice').value=p.pricePerKg||0;$('#newPriceUnit').value=p.priceUnit||'кг';$('#newPack').value=p.packKg||10;$('#newImg').value=p.img||'';$('#newDescRu').value=p.desc?.ru||'';$('#newVisible').checked=p.visible!==false;$('#modalEyebrow').textContent='Редактирование';$('#createTitle').textContent=title(p);$('#createBtn').textContent='Сохранить изменения';openModal()}
function openModal(){$('#createModal').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('#newNameRu').focus(),50)}
function closeModal(){$('#createModal').classList.add('hidden');document.body.style.overflow=''}
async function saveFullProduct(){const payload={nameRu:$('#newNameRu').value.trim(),nameEn:$('#newNameEn').value.trim(),catRu:$('#newCatRu').value.trim(),pricePerKg:Number($('#newPrice').value),priceUnit:$('#newPriceUnit').value,packKg:Number($('#newPack').value||10),img:$('#newImg').value.trim(),descRu:$('#newDescRu').value.trim(),visible:$('#newVisible').checked};if(!payload.nameRu||!payload.pricePerKg)throw new Error('Укажите название и цену');if(editingId){const data=await api(`/api/admin/products/${editingId}`,{method:'POST',body:JSON.stringify(payload)}),index=products.findIndex(p=>p.id===editingId);products[index]=data.product;setStatus('Изменения сохранены')}else{const data=await api('/api/admin/products',{method:'POST',body:JSON.stringify(payload)});products.push(data.product);setStatus('Товар добавлен')}closeModal();renderProducts();renderCategories();updateStats()}
async function uploadImage(file){if(!file)return;const form=new FormData();form.append('image',file);$('#uploadStatus').textContent='Загружаем изображение…';const data=await api('/api/admin/upload',{method:'POST',body:form});$('#newImg').value=data.path;$('#uploadStatus').textContent='Изображение загружено'}
async function removeProduct(card){const p=products.find(x=>Number(x.id)===Number(card.dataset.id));if(!confirm(`Удалить «${title(p)}»?`))return;await api(`/api/admin/products/${p.id}`,{method:'DELETE'});products=products.filter(x=>x.id!==p.id);renderProducts();renderCategories();updateStats();setStatus('Товар удалён')}

function renderCategories(){const groups={};products.forEach(p=>(groups[category(p)]??=[]).push(p));$('#categoryGroups').innerHTML=Object.entries(groups).map(([name,items])=>`<section class="category-block"><header><div><h3>${esc(name)}</h3><small>${items.length} товаров</small></div></header><div>${items.map((p,index)=>`<article class="sort-item" data-id="${p.id}"><span class="drag">⠿</span><img src="/${esc(p.img||'assets/p1.jpg')}" alt=""><b>${esc(title(p))}</b><div><button data-move="up" ${index===0?'disabled':''}>↑</button><button data-move="down" ${index===items.length-1?'disabled':''}>↓</button></div></article>`).join('')}</div></section>`).join('')||'<div class="empty">Категорий пока нет</div>'}
async function moveProduct(id,direction){const index=products.findIndex(p=>p.id===id),p=products[index],same=products.map((x,i)=>({x,i})).filter(v=>category(v.x)===category(p)),pos=same.findIndex(v=>v.x.id===id),target=same[pos+(direction==='up'?-1:1)];if(!target)return;[products[index],products[target.i]]=[products[target.i],products[index]];const data=await api('/api/admin/products/reorder',{method:'POST',body:JSON.stringify({ids:products.map(x=>x.id)})});products=data.products;renderProducts();renderCategories();setStatus('Порядок сохранён')}
async function loadHistory(){const data=await api('/api/admin/history');$('#historyList').innerHTML=(data.history||[]).map(item=>`<article><span>₽</span><div><b>${esc(item.productName)}</b><small>${new Date(item.changedAt).toLocaleString('ru-RU')}</small></div><div class="price-change"><del>${money(item.oldPrice)}</del><strong>${money(item.newPrice)}</strong></div></article>`).join('')||'<div class="empty">Изменений цен пока нет</div>'}
async function loadNotifications(){const data=await api('/api/admin/notifications');$('#notifyOrders').checked=data.settings.newOrders;$('#notifyStock').checked=data.settings.lowStock}
async function saveNotifications(){await api('/api/admin/notifications',{method:'POST',body:JSON.stringify({newOrders:$('#notifyOrders').checked,lowStock:$('#notifyStock').checked})});setStatus('Настройки уведомлений сохранены')}
async function importPrice(file){if(!file)return;const form=new FormData();form.append('price',file);setStatus('Импортируем прайс…');const data=await api('/api/admin/import-price',{method:'POST',body:form});await loadProducts();setStatus(`Прайс импортирован: добавлено ${data.added}, обновлено ${data.updated}, без цены ${data.unavailable||0}`)}
async function sendOffer(){const text=$('#offerText').value.trim();if(!text)throw new Error('Введите текст предложения');if(!confirm('Отправить это предложение всем подписчикам бота?'))return;const data=await api('/api/admin/broadcast',{method:'POST',body:JSON.stringify({text})});setStatus(`Рассылка завершена: отправлено ${data.sent}, ошибок ${data.failed}`)}

function switchSection(section){currentSection=section;$$('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===section));$('.catalog-panel').classList.toggle('hidden',section!=='catalog');$('#categoriesView').classList.toggle('hidden',section!=='categories');$('#historyView').classList.toggle('hidden',section!=='history');$('#notificationsView').classList.toggle('hidden',section!=='notifications');$('#offersView').classList.toggle('hidden',section!=='offers');$('.stats').classList.toggle('hidden',section!=='catalog');$('#openCreateBtn').classList.toggle('hidden',section!=='catalog');$('#importPriceBtn').classList.toggle('hidden',section!=='catalog');const names={catalog:'Каталог товаров',categories:'Категории',history:'История цен',notifications:'Уведомления',offers:'Холодные предложения'};$('#pageHeading').textContent=names[section];if(section==='history')loadHistory().catch(e=>setStatus(e.message,false));if(section==='notifications')loadNotifications().catch(e=>setStatus(e.message,false))}

$('#password').value=adminPassword;
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();adminPassword=$('#password').value.trim();$('#loginStatus').textContent='';try{await loadProducts();sessionStorage.setItem('ADMIN_PASSWORD',adminPassword)}catch(error){$('#loginStatus').textContent=error.message||'Неверный пароль'}});
$('#togglePassword').onclick=()=>{const el=$('#password');el.type=el.type==='password'?'text':'password'};
$('#reloadBtn').onclick=()=>loadProducts().catch(e=>setStatus(e.message,false));$('#search').oninput=renderProducts;$('#openCreateBtn').onclick=openCreate;$('#createBtn').onclick=()=>saveFullProduct().catch(e=>setStatus(e.message,false));$('#imageUpload').onchange=e=>uploadImage(e.target.files[0]).catch(err=>{$('#uploadStatus').textContent=err.message});$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('ADMIN_PASSWORD');location.reload()};$('#saveNotifications').onclick=()=>saveNotifications().catch(e=>setStatus(e.message,false));$('#testNotification').onclick=()=>api('/api/admin/notifications/test',{method:'POST',body:'{}'}).then(()=>setStatus('Тест отправлен в Telegram')).catch(e=>setStatus(e.message,false));
$('#priceImport').onchange=e=>importPrice(e.target.files[0]).catch(x=>setStatus(x.message,false));$('#offerText').oninput=e=>$('#offerPreview').textContent=e.target.value||'Здесь появится текст рассылки';$('#sendOffer').onclick=()=>sendOffer().catch(e=>setStatus(e.message,false));
$$('[data-close-modal]').forEach(el=>el.onclick=closeModal);$$('[data-section]').forEach(el=>el.onclick=()=>switchSection(el.dataset.section));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.addEventListener('click',e=>{const card=e.target.closest('.product');if(card){if(e.target.closest('[data-save]'))saveQuick(card).catch(x=>setStatus(x.message,false));if(e.target.closest('[data-toggle]'))toggleVisible(card).catch(x=>setStatus(x.message,false));if(e.target.closest('[data-edit]'))openEdit(card.dataset.id);if(e.target.closest('[data-delete]'))removeProduct(card).catch(x=>setStatus(x.message,false))}const move=e.target.closest('[data-move]');if(move){const item=move.closest('.sort-item');moveProduct(Number(item.dataset.id),move.dataset.move).catch(x=>setStatus(x.message,false))}});
if(adminPassword)loadProducts().catch(()=>sessionStorage.removeItem('ADMIN_PASSWORD'));
